name: client_cookie
description: Emulates Cookie store for dart:io and Flutter like its a Browser
version: 0.1.0
homepage: https://github.com/Jaguar-dart/client_cookie
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.0

dev_dependencies:
  test: ^0.12.0
